Dockerfile: install e2fsprogs to fix missing mkfs.ext4
It's used in at least one test;

    === FAIL: amd64.integration-cli TestDockerDaemonSuite/TestDaemonNoSpaceLeftOnDeviceError (0.11s)
        docker_cli_daemon_test.go:1065: assertion failed:
            Command:  mkfs.ext4 -F /tmp/no-space-left-on-device-test183525913/testfs.img
            ExitCode: 127
            Error:    exec: "mkfs.ext4": executable file not found in $PATH
            Stdout:
            Stderr:

            Failures:
            ExitCode was 127 expected 0
            Expected no error
        --- FAIL: TestDockerDaemonSuite/TestDaemonNoSpaceLeftOnDeviceError (0.11s)

Signed-off-by: Sebastiaan van Stijn <github@gone.nl>